name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 19 * * 3'

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpango1.0-dev libgraphene-1.0-dev libgtk-4-dev

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, rust-src

      - name: Install cargo plugins
        run: |
          cargo install cargo-rdme
          cargo install cargo-deadlinks

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check everything
        run: bash ./tools/check.sh

  msrv:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpango1.0-dev libgraphene-1.0-dev libgtk-4-dev

      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo plugins
        run: cargo install cargo-msrv

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check the minimum supported rust version
        run: cargo msrv verify
