name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 19 * * 3'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # TODO Change this to `ubuntu-latest` once it is updated to 22.04.
        os: [ubuntu-22.04]

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpango1.0-dev libgraphene-1.0-dev libgtk-4-dev

      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true
          components: rustfmt, rust-src

      - name: Install cargo plugins
        run: |
          cargo install cargo-rdme
          cargo install cargo-deadlinks

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check everything
        run: bash ./tools/check.sh
