name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}

    # TODO Change this to `ubuntu-latest` once it is updated to 22.04.
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.zst tar.bz2

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpango1.0-dev libgraphene-1.0-dev libgtk-4-dev

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Build release binary
        uses: rust-build/rust-build.action@v1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          TOOLCHAIN_VERSION: stable
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          EXTRA_FILES: "README.md LICENSE.md"
